name: James Doshin Benton
favicon: null
layout_spectrum: 0.97668
typography_spectrum: 0.47817
title: James Doshin Benton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211d27'
    - '#cccdb8'
    - '#a59f97'
    - '#59556b'
    - '#7b7072'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
