name: James Doshin Benton
favicon: null
layout_spectrum: 0.8514074112754315
typography_spectrum: 0.30634
title: James Doshin Benton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211d27'
    - '#cccdb8'
    - '#a59f97'
    - '#59556b'
    - '#7b7072'
  brandStrength: 0.5914303211029619
  lightness: 0.25
  saturation: 0.23833535029552877
  rhythmicContrast: 0.75
purpose: []
